#Debug output
PRINT_ELAPSED_TIME = True

#Grid default settings
SIZE = WIDTH, HEIGHT = 40, 40
PROBABILITY = 0.5

#Instruments settings
MAX_GRID = 100
MAX_LINE_LENGHT = 30
MAX_LINE_WIDTH = 20
MAX_POINT_RADIUS = 20
PROBABILITY_STEP = 0.05
SCALE_LENGHT = 300

#Canvas draw settings
PADDING = 20
LINE_LENGHT = 20
LINE_WIDTH = 10
POINT_DIAMETER = 10
BACKGROUND_COLOR = 'pink'